### ISSUE TITLE
请问是如何训练得到的这个tokenizer？

### ISSUE THREAD

**Issue by xinpengzz** [CanvaChen/chinese-llama-tokenizer#1]
感谢您的开源！
请问您是如何训练的呢？这部分代码有计划开源吗？

**Comment by CanvaChen** [comment]
没有采取训练的方式，是先收集中英文词典的字词，然后和已训练过的tokenizer（baichuan2和llama3）取交集。如果是从文本训练来的，会生成一些并非实际的词语，所以没有采取这种方式。

**Comment by xinpengzz** [comment]
感谢您的回复！
